http:
  host: 'localhost'
  port: 8080

database:
  host: ${DATABASE_HOST}
  port: "3306"
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}


jwt:
  secret_key_acceess: ${SECRET_KEY_ACCESS}
  secret_key_refresh: ${SECRET_KEY_REFRESH}


